name: ZSAPIClient
options:
  bundleIdPrefix: com.yeager
targets:
  ZSAPIClient:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yeager.zs-api-client
        PRODUCT_NAME: ZS API Client
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: NO
        INFOPLIST_FILE: Sources/Info.plist
